import type { Metadata } from "next";
import { Pacifico, Poppins } from "next/font/google";
import AnnouncementBar from "./_components/theme/global/AnnouncementBar";
import Header from "./_components/theme/global/Header";
import Footer from "./_components/theme/global/Footer";

import "./globals.css";

const pacifico = Pacifico({
    subsets: ["latin"],
    weight: "400", // only 400 is available
    variable: "--font-pacifico",
});

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "600"], // You can choose multiple weights if needed
    variable: "--font-poppins", // optional for Tailwind
});

export const metadata: Metadata = {
    title: "Pistorium | Home",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${pacifico.variable} ${poppins.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
