import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Pistorium | Checkout",
    description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main className="bg-yellow-50 text-[var(--background)]">
        {children}
      </main>
  );
}