import type { Metadata } from "next";
import PageRender from "../_components/theme/PageRender";

export const metadata: Metadata = {
    title: "Pistorium | Product",
    description: "Generated by create next app",
};

export default function CheckoutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <PageRender>
            {children}
        </PageRender>
    );
}
